# Generated by Django 4.0.6 on 2022-07-07 11:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.GenericIPAddressField(verbose_name='Ip адрес')),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65536)], verbose_name='Порт')),
                ('resource', models.CharField(choices=[('Win', 'Windows'), ('Unix', 'UNIX'), ('SQL', 'SQL')], max_length=50, verbose_name='Ресурс')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Хост',
                'verbose_name_plural': 'Хосты',
                'ordering': ['ip_adress'],
            },
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(fields=('ip_adress', 'port'), name='uniq host/port'),
        ),
    ]
