# Generated by Django 4.0.6 on 2022-07-07 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add_host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='owners',
            field=models.ManyToManyField(related_name='hosts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
